export * from './listsAction';
export * from './itemActions';
export * from './boardActions';
export * from './activeActionts';
export * from './userActions';

export const CONSTANTS = {
  ADD_ITEM: 'ADD_ITEM',
  ADD_LIST: 'ADD_LIST',
  DRAG_HAPPENED: 'DRAG_HAPPENED',
  INIT_BOARDS: 'INIT_BOARDS',
  LOAD_BOARD_DATA: 'LOAD_BOARD_DATA',
  CREATE_NEW_LIST: 'CREATE_NEW_LIST',
  CREATE_NEW_ITEM: 'CREATE_NEW_ITEM',
  SET_NEW_ACTIVE_BOARD: 'SET_NEW_ACTIVE_BOARD',
  UPDATE_ACTIVE_BOARD: 'UPDATE_ACTIVE_BOARD',
  CREATE_NEW_BOARD: 'CREATE_NEW_BOARD',
  REMOVE_LIST: 'REMOVE_LIST',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REMOVE_BOARD: 'REMOVE_BOARD',
  CREATE_TEMPLATE: 'CREATE_TEMPLATE',
  GET_TEMPLATES: 'GET_TEMPLATES',
  DELETE_TEMPLATE: 'DELETE_TEMPLATE',
};
